src/Entity/Annonce.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnnonceRepository")
 */
class Annonce
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="annoncesCreees")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_createur;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Utilisateur", inversedBy="annoncesParticipees")
     */
    private $participants;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $intitule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbMaxParticipants;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="annonces")
     */
    private $id_categorie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Departement", inversedBy="annonces")
     */
    private $id_departement;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getIntitule();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdCreateur(): ?Utilisateur
    {
        return $this->id_createur;
    }

    public function setIdCreateur(?Utilisateur $id_createur): self
    {
        $this->id_createur = $id_createur;

        return $this;
    }

    /**
     * @return Collection|Utilisateur[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Utilisateur $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
        }

        return $this;
    }

    public function removeParticipant(Utilisateur $participant): self
    {
        if ($this->participants->contains($participant)) {
            $this->participants->removeElement($participant);
        }

        return $this;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getNbMaxParticipants(): ?int
    {
        return $this->nbMaxParticipants;
    }

    public function setNbMaxParticipants(int $nbMaxParticipants): self
    {
        $this->nbMaxParticipants = $nbMaxParticipants;

        return $this;
    }

    public function getIdCategorie(): ?Categorie
    {
        return $this->id_categorie;
    }

    public function setIdCategorie(?Categorie $id_categorie): self
    {
        $this->id_categorie = $id_categorie;

        return $this;
    }

    public function getIdDepartement(): ?Departement
    {
        return $this->id_departement;
    }

    public function setIdDepartement(?Departement $id_departement): self
    {
        $this->id_departement = $id_departement;

        return $this;
    }
}

src/Form/AnnonceType.php
<?php

namespace App\Form;

use App\Entity\Annonce;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnnonceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('intitule')
            ->add('description')
            ->add('date')
            ->add('nbMaxParticipants')
            ->add('id_categorie')
            ->add('id_departement')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Annonce::class,
        ]);
    }
}

src/Controller/AnnonceController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Form\AnnonceType;
use App\Repository\AnnonceRepository;
use Cassandra\Date;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/annonce")
 */
class AnnonceController extends AbstractController
{
    /**
     * @Route("/", name="annonce_index", methods={"GET"})
     */
    public function index(AnnonceRepository $annonceRepository): Response
    {
        return $this->render('annonce/index.html.twig', [
            'annonces' => $annonceRepository->findAll(),
            'annonces_user' => $this->getUser()->getAnnoncesCreees(),
            'user' => $this->getUser()
        ]);
    }

    /**
     * @Route("/new", name="annonce_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $annonce = new Annonce();
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        $annonce->setIdCreateur($this->getUser());
        $annonce->setDateCreation(new \DateTime());

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($annonce);
            $entityManager->flush();

            return $this->redirectToRoute('annonce_index');
        }

        return $this->render('annonce/new.html.twig', [
            'annonce' => $annonce,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="annonce_show", methods={"GET"})
     */
    public function show(Annonce $annonce, $id): Response
    {
        $max = $annonce->getNbMaxParticipants();
        $partActu = sizeof($annonce->getParticipants());
        return $this->render('annonce/show.html.twig', [
            'annonce' => $annonce,
            'max' => $max,
            'partActu' => $partActu
        ]);
    }

    /**
     * @Route("/detail/{id}", name="annonce_showPerso", methods={"GET"})
     */
    public function showPerso(Annonce $annonce): Response
    {
        $max = $annonce->getNbMaxParticipants();
        $partActu = sizeof($annonce->getParticipants());
        return $this->render('annonce/showPerso.html.twig', [
            'annonce' => $annonce,
            'max' => $max,
            'partActu' => $partActu
        ]);
    }

    /**
     * @Route("/add/{id}", name="add_participant", methods={"GET","POST"})
     */
    public function addParticipant(Annonce $annonce): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $lannonce = $entityManager->getRepository(Annonce::class)->find($annonce->getId());
        $lannonce->addParticipant($this->getUser());
        $entityManager->flush();

        $participants = $lannonce->getParticipants();
        return $this->redirectToRoute('annonce_showPerso',['id' => $annonce->getId()]);

    }

    /**
     * @Route("/{id}/edit", name="annonce_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Annonce $annonce): Response
    {
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('annonce_index');
        }

        return $this->render('annonce/edit.html.twig', [
            'annonce' => $annonce,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="annonce_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Annonce $annonce): Response
    {
        if ($this->isCsrfTokenValid('delete'.$annonce->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($annonce);
            $entityManager->flush();
        }

        return $this->redirectToRoute('annonce_index');
    }
}

templates/annonce/_delete_form.html.twig
<form method="post" action="{{ path('annonce_delete', {'id': annonce.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ annonce.id) }}">
    <button class="btn">Delete</button>
</form>

templates/annonce/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default("DEPOSER L'ANNONCE") }}</button>
{{ form_end(form) }}

templates/annonce/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Annonce{% endblock %}

{% block body %}
    <h1>Edit Annonce</h1>

    {{ include('annonce/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('annonce_index') }}">back to list</a>

    {{ include('annonce/_delete_form.html.twig') }}
{% endblock %}

templates/annonce/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce index{% endblock %}

{% block body %}


    <nav class="v2">
        <a href="/" class="logo"><img src="{{ asset('assets/img/logoJauneC.svg') }}" alt=""></a>
        <ul>
            <li><a href="{{ path('annonce_index') }}">Mon compte</a></li>
            <li><a href="{{ path('annonce_new') }}">Proposer mes services</a></li>
            {% if is_granted('ROLE_USER') %}
                <li><a href="/logout" class="connexion">Deconnexion</a></li>
                {% else %}
                    <li><a href="{{ path('register') }}">Inscription</a></li>
                    <li><a href="{{ path('app_login') }}" class="connexion">Connexion</a></li>
            {% endif %}
        </ul>
    </nav>

    <section class="atelier">
        <section style="display: flex;flex-direction: column; height: 70vh;background-color: transparent">
            {% for annonce in annonces_user %}
            <section style="height: 70%;display: block">
                <article class="img-atelier" style="background:url({{ asset('assets' ~ annonce.idCategorie.image ) }}) center;background-size: cover;"></article>
                <p style="margin-top: 10px; float: right;margin-right: 20px">Crée le {{ annonce.dateCreation|date("m/d/Y") }}</p>
                <h1 style="font-size:1.3vw;margin-top: 10px">{{ annonce.intitule }}</h1>
                <h3 style="font-size:1vw;margin-bottom: 10px">{{ annonce.idCategorie.nom }}</h3>
                <h2 style="font-weight: 700;font-size: 1vw;margin-bottom: 10px">Description</h2>
                <p style="color: rgba(29,33,36,0.73)font-size:0.8vw">{{ annonce.description }}</p>
                <div class="bar" style="margin-top: 10px;margin-bottom: 5px;margin-left:5%;width: 90%;height: 1px;background-color: rgba(169,169,169,0.53);"></div>
                <article style=" display: flex;">
                    <p><i class="fas fa-map-marker-alt"></i> {{ annonce.idDepartement.nom }}</p>
                    <p><i class="far fa-clock"></i> {{ annonce.date|date("m/d/Y") }}</p>
                    <a style="color: white;font-weight: 700; margin-left:15px;display:flex;align-items:center;justify-content:center;border-radius:10px;width: 20%;height: 50px;background-color: #f2c335" href="{{ path('annonce_show', {'id': annonce.id}) }}">Voir l'annonce</a>
                    <a style="color: white;font-weight: 700; margin-left:15px;display:flex;align-items:center;justify-content:center;border-radius:10px;width: 20%;height: 50px;background-color: #f2c335" href="{{ path('annonce_edit', {'id': annonce.id}) }}">Modifier</a>
                </article>
            </section>
            {% endfor %}
        </section>
        <section style="text-align: center;display:flex;flex-direction: column;align-items: center">
            <div class="img-ut" style="margin-top: 50px; width:100px;height:100px;border-radius:100px;background:url({{ asset('assets/img/icon.png') }}) center;background-size: cover;"></div>
            <h2 style="padding-left: 0;margin-top:15px;font-size: 1.3vw;font-weight: 700">{{ user.prenom }}</h2>
            <p style="padding-left: 0;margin-top:5px;font-size: 0.9vw;color: grey"><i class="fas fa-map-marker-alt"></i> {{ user.ville }}</p>
            <p style="padding-left: 0;margin-top:15px;margin-bottom: 15px"><img src="{{ asset('assets/img/food.svg') }}" alt="" width="10%"></p>
            <a style="margin-top:10px;color:white;font-weight:700;width: 80%;border-radius:10px;height: 50px;background-color: #D94A64;display: flex;justify-content: center;align-items: center" href="{{ path('annonce_new') }}">Create new</a>
            <h2 style="margin-top: 10px;padding:0;font-weight: 700;font-size: 1.2vw">Mes participations</h2>
            <div style="margin-top:15px;padding: 10px;background-color: rgba(128,128,128,0.13); height: 40%;width: 80%;border-radius: 10px">
                {% for part in user.annoncesParticipees %}
                    <article style="margin-bottom:10px;display:flex;justify-content:center;align-items:center;color:white;font-weight:700;border-radius:5px;background-color:#f2c335;width: 100%;height: 30px">{{ part.intitule }}</article>
                {% endfor %}
            </div>
        </section>
    </section>

{% endblock %}

templates/annonce/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Annonce{% endblock %}

{% block body %}

<body class="accueil">
<nav class="v2">
    <a href="/" class="logo"><img src="{{ asset('assets/img/logoJauneC.svg') }}" alt=""></a>
    <ul>
        <li><a href="{{ path('annonce_index') }}">Mon compte</a></li>
        <li><a href="{{ path('annonce_new') }}">Proposer mes services</a></li>
        {% if is_granted('ROLE_USER') %}
            <li><a href="/logout" class="connexion">Deconnexion</a></li>
        {% else %}
            <li><a href="{{ path('register') }}">Inscription</a></li>
            <li><a href="{{ path('app_login') }}" class="connexion">Connexion</a></li>
        {% endif %}
    </ul>
</nav>

<main class="proposerUnAtelier">
    <div class="rectangleBlanc">
        <h2 style="font-weight: 700;">Proposer un atelier culinaire</h2>

        {{ include('annonce/_form.html.twig') }}
        <!-- <form>
            <div class="form-group">
                <label for="exampleFormControlInput1">Nom de l'annonce</label>
                <input type="" class="form-control" id="exampleFormControlInput1" placeholder="">
            </div>

            <div class="form-group">
                <label for="exampleFormControlTextarea1">Descriptif de l'atelier que vous proposez</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>

            <div class="form-group">
                <label for="exampleFormControlSelect1">Catégorie</label>
                <select class="form-control" id="exampleFormControlSelect1">
                    <option>Cuisine Française</option>
                    <option>Cuisine Indienne</option>
                    <option>Cuisine Italienne</option>
                    <option></option>
                </select>
            </div>

            <div class="form-group">
                <label for="exampleFormControlInput1">Date de l'évènement</label>
                <input type="" class="form-control" id="exampleFormControlInput1" placeholder="">
            </div>

            <div class="form-group">
                <label for="exampleFormControlSelect1">Nombre de participants</label>
                <select class="form-control" id="exampleFormControlSelect1">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                </select>
            </div>

            <div class="form-group">
                <label for="exampleFormControlSelect1">Département de l'évènement</label>
                <select class="form-control" id="exampleFormControlSelect1">
                    <option>Charente Maritime</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                </select>
            </div>
            <button>Déposer l'atelier</button>
        </form> -->



    </div>
</main>
    <a href="{{ path('annonce_index') }}">back to list</a>
{% endblock %}

templates/annonce/participantsAnnonce.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participants annonce{% endblock %}

{% block body %}

    {% for participant in participants %}
        <p>{{ participant.nom }}</p>
    {% endfor %}
{% endblock %}

templates/annonce/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce{% endblock %}

{% block body %}
    <nav class="v2">
        <a href="/" class="logo"><img src="{{ asset('assets/img/logoJauneC.svg') }}" alt=""></a>
        <ul>
            <li><a href="{{ path('annonce_index') }}">Mon compte</a></li>
            <li><a href="{{ path('annonce_new') }}">Proposer mes services</a></li>
            {% if is_granted('ROLE_USER') %}
                <li><a href="/logout" class="connexion">Deconnexion</a></li>
            {% else %}
                <li><a href="{{ path('register') }}">Inscription</a></li>
                <li><a href="{{ path('app_login') }}" class="connexion">Connexion</a></li>
            {% endif %}
        </ul>
    </nav>
    <p class="ariane">Annonces > {{ annonce.idCategorie.nom }} > {{ annonce.idDepartement.nom }} > Voir > {{ annonce.intitule }}</p>
    <section class="atelier">
        <section>
            <article class="img-atelier" style="background:url({{ asset('assets' ~ annonce.idCategorie.image ) }}) center;background-size: cover;"></article>
            <p style="margin-top: 10px; float: right;margin-right: 20px">Crée le {{ annonce.dateCreation|date("m/d/Y") }}</p>
            <h1 style="margin-top: 30px">{{ annonce.intitule }}</h1>
            <h3 style="margin-bottom: 50px">{{ annonce.idCategorie.nom }}</h3>
            <h2 style="font-weight: 700;font-size: 1.5vw;margin-bottom: 10px">Description</h2>
            <p style="line-height: 30px;color: rgba(29,33,36,0.73)">{{ annonce.description }}</p>
            <div class="bar" style="margin-top: 70px;margin-bottom: 20px;margin-left:5%;width: 90%;height: 1px;background-color: rgba(169,169,169,0.53);"></div>
            <article style=" display: flex;">
                <p><i class="fas fa-map-marker-alt"></i> {{ annonce.idDepartement.nom }}</p>
                <p><i class="far fa-clock"></i> {{ annonce.date|date("m/d/Y") }}</p>
                <a style="margin-top:-15px;color: white;font-weight: 700; margin-left:15px;display:flex;align-items:center;justify-content:center;border-radius:10px;width: 20%;height: 50px;background-color: #f2c335" href="{{ path('annonce_index') }}">Revenir a la liste</a>

                <a style="margin-top:-15px;color: white;font-weight: 700; margin-left:15px;display:flex;align-items:center;justify-content:center;border-radius:10px;width: 20%;height: 50px;background-color: #f2c335" href="{{ path('annonce_edit', {'id': annonce.id}) }}">Modifier</a>
            </article>
        </section>
        <section style="text-align: center;display:flex;flex-direction: column;align-items: center">
            <div class="img-ut" style="margin-top: 50px; width:100px;height:100px;border-radius:100px;background:url({{ asset('assets/img/icon.png') }}) center;background-size: cover;"></div>
            <h2 style="padding-left: 0;margin-top:15px;font-size: 1.3vw;font-weight: 700">{{ annonce.idCreateur.prenom }}</h2>
            <p style="padding-left: 0;margin-top:5px;font-size: 0.9vw;color: grey"><i class="fas fa-map-marker-alt"></i> {{ annonce.idCreateur.ville }}</p>
            <p style="padding-left: 0;margin-top:15px;margin-bottom: 15px"><img src="{{ asset('assets/img/food.svg') }}" alt="" width="10%"> {{ partActu }} / {{ max }}</p>
            {{ include('annonce/_delete_form.html.twig') }}
            <div style="margin-top:28px;padding: 10px;background-color: rgba(128,128,128,0.13); height: 40%;width: 80%;border-radius: 10px">
                {% for part in annonce.participants %}
                    <article style="margin-bottom:10px;display:flex;justify-content:center;align-items:center;color:white;font-weight:700;border-radius:5px;background-color:#f2c335;width: 100%;height: 30px">{{ part.prenom }}</article>
                {% endfor %}
            </div>

        </section>
    </section>


{% endblock %}

templates/annonce/showPerso.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce{% endblock %}

{% block body %}
    <nav class="v2">
        <a href="/" class="logo"><img src="{{ asset('assets/img/logoJauneC.svg') }}" alt=""></a>
        <ul>
            <li><a href="{{ path('annonce_index') }}">Mon compte</a></li>
            <li><a href="{{ path('annonce_new') }}">Proposer mes services</a></li>
            {% if is_granted('ROLE_USER') %}
                <li><a href="/logout" class="connexion">Deconnexion</a></li>
            {% else %}
                <li><a href="{{ path('register') }}">Inscription</a></li>
                <li><a href="{{ path('app_login') }}" class="connexion">Connexion</a></li>
            {% endif %}
        </ul>
    </nav>
    <p class="ariane">Annonces > {{ annonce.idCategorie.nom }} > {{ annonce.idDepartement.nom }} > Détails > {{ annonce.intitule }}</p>
    <section class="atelier">
        <section>
            <article class="img-atelier" style="background:url({{ asset('assets' ~ annonce.idCategorie.image ) }}) center;background-size: cover;"></article>
            <p style="margin-top: 10px; float: right;margin-right: 20px">Crée le {{ annonce.dateCreation|date("m/d/Y") }}</p>
            <h1 style="margin-top: 30px">{{ annonce.intitule }}</h1>
            <h3 style="margin-bottom: 50px">{{ annonce.idCategorie.nom }}</h3>
            <h2 style="font-weight: 700;font-size: 1.5vw;margin-bottom: 10px">Description</h2>
            <p style="line-height: 30px;color: rgba(29,33,36,0.73)">{{ annonce.description }}</p>
            <div class="bar" style="margin-top: 70px;margin-bottom: 20px;margin-left:5%;width: 90%;height: 1px;background-color: rgba(169,169,169,0.53);"></div>
            <article style=" display: flex;">
                <p><i class="fas fa-map-marker-alt"></i> {{ annonce.idDepartement.nom }}</p>
                <p><i class="far fa-clock"></i> {{ annonce.date|date("m/d/Y") }}</p>
            </article>
        </section>
        <section style="text-align: center;display:flex;flex-direction: column;align-items: center">
            <div class="img-ut" style="margin-top: 50px; width:100px;height:100px;border-radius:100px;background:url({{ asset('assets/img/icon.png') }}) center;background-size: cover;"></div>
            <h2 style="padding-left: 0;margin-top:15px;font-size: 1.3vw;font-weight: 700">{{ annonce.idCreateur.prenom }}</h2>
            <p style="padding-left: 0;margin-top:5px;font-size: 0.9vw;color: grey"><i class="fas fa-map-marker-alt"></i> {{ annonce.idCreateur.ville }}</p>
            <p style="padding-left: 0;margin-top:15px;margin-bottom: 15px"><img src="{{ asset('assets/img/food.svg') }}" alt="" width="10%"> {{ partActu }} / {{ max }}</p>
            <a style="color:white;font-weight:700;width: 80%;border-radius:10px;height: 50px;background-color: #D94A64;display: flex;justify-content: center;align-items: center" href="{{ path('add_participant', {'id': annonce.id}) }}">Participer</a>
            <div style="margin-top:28px;padding: 10px;background-color: rgba(128,128,128,0.13); height: 40%;width: 80%;border-radius: 10px">
                {% for part in annonce.participants %}
                <article style="margin-bottom:10px;display:flex;justify-content:center;align-items:center;color:white;font-weight:700;border-radius:5px;background-color:#f2c335;width: 100%;height: 30px">{{ part.prenom }}</article>
                {% endfor %}
            </div>

        </section>
    </section>
    <!--<table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ annonce.id }}</td>
        </tr>
        <tr>
            <th>Intitule</th>
            <td>{{ annonce.intitule }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ annonce.description }}</td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ annonce.date ? annonce.date|date('Y-m-d H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>Date_creation</th>
            <td>{{ annonce.dateCreation ? annonce.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>NbMaxParticipants</th>
            <td>{{ annonce.nbMaxParticipants }}</td>
        </tr>
        <tr>
            <th>Participants</th>
            {% for part in annonce.participants %}
            <td>{{ part.nom }}</td>
            {% endfor %}
        </tr>
        </tbody>
    </table> -->


{% endblock %}